### ISSUE TITLE
[documentation] Comparision to Rust Scan

### ISSUE THREAD

**Issue by yonas** [mrjackwills/havn#7]
How does [havn](https://github.com/mrjackwills/havn) compare to [RustScan](https://github.com/RustScan/RustScan)?

**Comment by mrjackwills** [comment]
[havn](https://www.github.com/mrjackwills/havn) is a single self-contain binary, whereas [RustScan]( https://github.com/RustScan/RustScan) requires the third party nmap application to function.


I suspect RustScan is more configurable, although the reason [havn](https://www.github.com/mrjackwills/havn) was created was due to my inability to easily start and run a RustScan instance – although this probably says more about me rather than the RustScan project.


It also appears that RustScan doesn’t have Docker containers nor binaries for other CPU platforms. [havn](https://www.github.com/mrjackwills/havn) is tested, built for, and works perfectly, on Linux x86, armv6, arm64, and Windows x86

**Comment by yonas** [comment]
Thanks!
